### post de datos
POST http://localhost:3000/actas
Content-Type: application/json

{
  "cliente": {
    "nombre": "Roger Borras",
    "cedula_ruc": "1721908000",
    "telefono": "0983129683",
    "correo": "pasante@correo.com",
    "direccion": "marianas"
  },
  "equipo": 2,
  "inspeccion_hw": {
    "teclado": true,
    "teclado_obs": "",
    "mouse": true,
    "mouse_obs": "",
    "camara": true,
    "camara_obs": "",
    "pantalla": true,
    "pantalla_obs": "",
    "parlantes": true,
    "parlantes_obs": "",
    "bateria": true,
    "bateria_obs": "",
    "carcasa": true,
    "carcasa_obs": "",
    "cargador": true,
    "cargador_obs": ""
  },
  "inspeccion_sw": {
    "sistema_operativo": true,
    "antivirus": true,
    "office": true,
    "navegadores": true,
    "compresores": true,
    "acceso_remoto": true,
    "nota": "x"
  },
  "adicionales": {
    "mouse": true,
    "mouse_obs": "si",
    "mochila": true,
    "mochila_obs": "si",
    "estuche": true,
    "estuche_obs": "si",
    "software1": true,
    "software1_obs": "si",
    "software2": true,
    "software2_obs": "si",
    "software3": true,
    "software3_obs": "si"
  },
  "acta": {
    "forma_pago": "efectivo",
    "precio": 40000,
    "usuario_id": 2
  },
  "observaciones": "x"
}
